# Generated by Django 5.0.4 on 2024-04-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="votes",
            field=models.IntegerField(default=1),
        ),
    ]
