# Generated by Django 5.0.4 on 2024-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0002_alter_vote_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="votes",
            field=models.IntegerField(default=1),
        ),
    ]
