# Generated by Django 5.0.4 on 2024-04-13 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0003_movie_votes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
